config/routes.rb
Rails.application.routes.draw do
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  post '/cart/checkout' => 'cart#checkout'
  resources :checkout
  resources :orders
  post '/checkout' => 'checkout#create'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'users#new'
  

  resources :users
  resources :groups
  resources :memberships
  resources :shirts
  post 'shirts/show_product'
  post 'shirts/show'
  post 'shirts/upload'

end

app/models/group.rb
class Group < ActiveRecord::Base
    
    has_many :memberships
    has_many :users, through: :memberships
    
    def self.create_group!(group_params)
        group_params[:group_id] = loop do
          token = SecureRandom.urlsafe_base64
          break token unless Group.exists?(:group_id => token)
        end
        #group_params[:group_id]=SecureRandom.base64
        Group.create!(group_params)
    end
    
    def self.add_members!(accept_params)
        #puts group_params
        #Membership.create!(accept_params)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def group_params
    params.require(:group).permit(:group_id, :admin_id, :group_name, :accept => [])
  end
  
  def acceptDeny_params
    params.require(:acceptDeny).permit(:accept, :deny)
  end

  def show
    @group = Group.find_by(:group_id => params[:group_id])
    @groups = Group.where(:admin_id => current_user.id) #need this here for navbar to work on groups pages
    @memberships = Membership.where(:group_id => params[:group_id])
    @members = Membership.where(:group_id => params[:group_id], :accepted => true)
    puts @members
    @newusers = {}
    cookies[:group_id]=params[:group_id]
    @memberships.each do |membership|
      if membership.accepted == false
        
        @addUser = User.find_by(:email => membership.user_id)
        if !@addUser.nil?
          @newusers[@addUser] = membership
          puts @newusers
        else
          puts "not found"
          puts membership.user_id
        end
      end
    end
  end

  def index
    
  end

  def new
    # default: render 'new' template
    @groups = Group.where(:admin_id => current_user.id) #need this here for navbar to work on groups pages
  end

  def create
    
    if !current_user.nil?
      group_params[:admin_id]=current_user.id
      Group.create_group!(group_params)
      
    end
    redirect_to authenticated_root_path
  end

  def edit
    
  end

  def update
    @newMembersToDeny = params[:deny]
    @newMembersToAccept = params[:accept]
    if @newMembersToDeny.nil?
      @newMembersToDeny = []
    end
    if @newMembersToAccept.nil?
      @newMembersToAccept = []
    end
    
    @checkedBoth = []

    if(!(@newMembersToDeny.empty? || @newMembersToAccept.empty?))
      @newMembersToDeny.each do |user|
          puts user
          if @newMembersToAccept.include?(user)
            puts "checked both"
            @checkedBoth << user
          end
      end
    end
    
    if(!@newMembersToDeny.nil?)
      @newMembersToDeny.each do |user, membership|
        if(!@checkedBoth.include?(user))
          @toDelete = Membership.find_by(:user_id => user, :group_id => params[:group][:group_id] )
          @toDelete.destroy
        end
      end
    end
   
    if(!@newMembersToAccept.nil?)
      @newMembersToAccept.each do |user|
        if(!@checkedBoth.include?(user))
          puts user
          @toChange = Membership.find_by(:user_id => user, :group_id => params[:group][:group_id] )
          @toChange.update_attribute(:accepted, true)
          puts @toChange
        end
      end
    end
    
    redirect_to group_path(:group_id => params[:group][:group_id])
  end

  def destroy
    
  end

end

app/views/groups/new.html.erb
<div class = "text-center">
  <%= render "layouts/navbar" %>
  <h2>Create Group</h2>
  <%= form_tag groups_path do %>
  <div class = "row">
    <div class = "form-group col-md-4 col-md-offset-4">
      <hr>
      <div class = "field">
        <%= text_field :group,'group_name', placeholder: 'Group Name',:id => 'signup_user' %>
        <%= text_field :group, 'admin_id',:id => 'signup_email',:value => current_user.id,:readonly => true,:type =>'hidden' %>
       
        <%= submit_tag 'Create Group', class: "submitTag btn btn-success btn-block", :id => 'signup_create' %>
        <br/>
        <%= link_to 'Cancel', authenticated_root_path , :id => 'cancel'%>
      </div>
    </div>
  </div>
    
    
    
  <% end %>
</div>

app/views/groups/show.html.erb
<div class = "text-center">
  <%= render "layouts/navbar" %>
  <h2>Admin Page for <%= @group.group_name %></h2>
  <div class = "row">
    <div class ="col-md-4 col-md-offset-4">
      <hr>
    </div>
  </div>
  <%= link_to 'Create Garment', shirts_path%>

  <% if @newusers.count > 0 %>
    <div class="row", id="userheader">
      <h3>Users that want to join your group:</h3>
      <div class ="col-md-4 col-md-offset-4"><hr></div>
      <div class="col-md-2 col-md-offset-3"><u>Name</u></div>
      <div class="col-md-2"><u>Accept</u></div>
      <div class="col-md-2"><u>Deny</u></div>
      
      <%= form_for(@group, :url => group_path, :method => :patch) do |f| %>
        <%= text_field :group,'group_name', :value => @group.group_name, :readonly => true, :hidden => true %>
        <%= text_field :group, 'admin_id',:id => 'signup_email',:value => @group.admin_id,:readonly => true, :hidden => true %>
        <%= text_field :group, 'group_id', :id => 'group_id', :value => @group.group_id, :readonly => true, :hidden => true %>
        
        <% @newusers.each do |user,membership| %>
          <div style="height:30px;"></div>
          <div class="row">
            <div class="col-md-2 col-md-offset-3"><%= user.username %></div> 
            <div class="col-md-2"><%= check_box_tag 'accept[]', user.email %></div>
            <div class="col-md-2"><%= check_box_tag 'deny[]',  user.email  %></div>
          </div>
        <% end %>
        <div class="col-md-4 col-md-offset-4">
          <div class="actions">
            <%= f.submit "update",class: 'btn btn-success btn-block' %>
          </div>
        </div>
      <% end %>

    </div>
  <% end %>
  <br/>
  <br/>
  <div class = "row">
    <div class ="col-md-4 col-md-offset-4">
      <h3>Current Members:</h3>
      <hr>
      <% @members.each do |membership| %>
        <h4><%= membership.user_id %></h4>
        
      <%end%>
    </div>
    
  </div>
</div>