config/routes.rb
Rails.application.routes.draw do
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  post '/cart/checkout' => 'cart#checkout'
  resources :checkout
  resources :orders
  post '/checkout' => 'checkout#create'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'users#new'
  

  resources :users
  resources :groups
  resources :memberships
  resources :shirts
  post 'shirts/show_product'
  post 'shirts/show'
  post 'shirts/upload'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @groups = Group.where(:admin_id => current_user.id)
        @myMemberships = Membership.where(:user_id => current_user.email)
        @Orders = Order.where(:user_id => current_user.email)
        @myOrders = []
        @Orders.each do |order|
            puts order.design_id
            shirt = Shirt.where(:design_id => order.design_id)
            puts shirt
            shirt.each do |shirt|
                puts shirt
                orderHash = {}
                orderHash["shirt"] = shirt
                orderHash["order"] = order
                orderHash["product"] = JSON.parse(RestClient.get("https://test_pNOw-AjW1Pz73UNPKb3F2g:@api.scalablepress.com/v2/products/#{shirt.product}"))
                @myOrders.push(orderHash)
            end
            
        end
        @myGroups = Hash.new
        @myMemberships.each do |membership|
            if membership.accepted == true
                group = (Group.where(:group_id => membership.group_id))
                group.each do |g|
                    shirts = Shirt.where(:group_id => g.group_id)
                    #puts shirts
                    sArr = Array.new
                    shirts.each do |s|
                        if s.product
                            #puts s.product
                            newS = Hash.new()
                            newS["shirt"] = s
                            
                            product = JSON.parse(RestClient.get("https://test_pNOw-AjW1Pz73UNPKb3F2g:@api.scalablepress.com/v2/products/#{s.product}"))
                            #price = JSON.parse(RestClient.get("https://test_pNOw-AjW1Pz73UNPKb3F2g:@api.scalablepress.com/v2/products/#{s.product}/items"))
                            
                           
                            newS["product"] = product
                            sArr.push(newS)
                            #puts s
                        end
                   end
                   @myGroups[g.group_id] = {"shirts" => sArr, "group" => g}

                end
                #puts @myGroups
            end
        end
        @groups.each do |g|
            shirts = Shirt.where(:group_id => g.group_id)
            #puts shirts
            sArr = Array.new
            shirts.each do |s|
                if s.product
                    puts s.product
                    newS = Hash.new()
                    newS["shirt"] = s
                    
                    product = JSON.parse(RestClient.get("https://test_pNOw-AjW1Pz73UNPKb3F2g:@api.scalablepress.com/v2/products/#{s.product}"))
                    newS["product"] = product
                    sArr.push(newS)
                    puts s
                end
            @myGroups[g.group_id] = {"shirts" => sArr, "group" => g}

            end
        end
        @allgroups = Group.all
        @allGroupsNotMine = Array.new
        @allgroups.each do |group|
            member = Membership.where(:group_id => group.group_id, :user_id => current_user.email, :accepted => true)
            #puts member
           if group.admin_id.to_s == current_user.id.to_s
             #  puts group.admin_id
           elsif member.exists?
            #   puts "already in group"
           else
               @allGroupsNotMine.push(group)
           end

        end
        @currentUser = nil
        if !current_user.nil?
            @currentUser = current_user
        end
    end
    
    def update
       
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class = "text-center">
  <%= render "layouts/navbar" %>


    <% if !@myMemberships.nil? %>
      <% @myMemberships.each do |membership| %>
       
      <% end %>
    <% end %>
  <h2>My Groups</h2>
  <div class = "row">
    <div class = "col-md-4 col-md-offset-4">
      <hr>
    </div>
  </div>
  <% if !@myGroups.nil? %>
    <% @myGroups.each do |key, group| %>
      <h3><%=group["group"].group_name%></h3>
      <% if !group["shirts"].empty? %>
        <% group["shirts"].in_groups_of(3,false).each do |shirts|%>
          <div class="row">
            <div class = "col-md-offset-2">
              <% shirts.each do |s| %>
                <div class = "col-md-3">
                  <div class = "card card-block">
                    <div class="card-title"><h5><%= s["product"]["name"] %></h5></div>
                    </br>
                    <% if s["shirt"].price.nil? %>
                      <div class="card-content">N/A</div>
                    <% else %>
                      <div class="card-content">$<%= s["shirt"].price %></div>
                    <% end %>
                    </br>
                    <div class="card-content"><%= s["shirt"].delivery_address %></div>
                    </br>
                    <div class="card-content"><%= s["shirt"].end_date %></div>
                    <div class="row">
                      <div class="col-xs-6">
                        <h5>Design</h5>
                      </div>
                      <div class="col-xs-6">
                        <h5>Style</h5>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-xs-6">
                        <img id = "shirtHomeImg" src=<%=s["shirt"].image_url%>></img>
                      </div>
                      <% @helper = [] %>
                      <div class="col-xs-6">
                        <% @productColor = s["product"]["colors"].select{|color| color["name"] == s["shirt"].color} %>
                          <% if @productColor==@helper %>
                            <img id = "shirtHomeImg" src=<%=s["product"]["image"]["url"]%>></img>
                          <% else %>
                            <% @imageColor = @productColor[0]["images"].select{|image| image["label"] == "Front"} %>
                            <% if @imageColor==@helper %>
                              <% @imageColor = @productColor[0]["images"][0] %>
                            <% end %>
                            <img id = "shirtHomeImg" src=<%= @imageColor[0]["url"] %>></img>
                          <% end %>  
                      </div>
                      <p><a href="/cart/<%= s["shirt"].design_id %>">Add to Cart</a></p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        
      <% else %>
        <h4>This group does not have any current shirts</h4>
      <%end %>
    <% end %>
  <% end %>
  <h2>Groups to Join</h2>
  <div class = "row">
    <div class = "col-md-4 col-md-offset-4">
      <hr>
    </div>
  </div>
    <% @allGroupsNotMine.each do |group| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= text_field :group,'group_name', :value => group.group_name, :readonly => true, :hidden => true %>
          <%= text_field :group, 'admin_id',:id => 'signup_email',:value => group.admin_id,:readonly => true, :hidden => true %>
          <%= text_field :group, 'group_id', :id => 'group_id', :value => group.group_id, :readonly => true, :hidden => true %>
          <%= text_field :id, 'id', :value => group.group_id_id, :readonly => true, :hidden => true %>
          <div class = "well">
            <h3><%= group.group_name %></h3> 
            <%= link_to("Join!", memberships_path(group,:group_id => group.group_id),:method => :post) %>
          </div>
        </div>
      </div>
    <% end %>

    <h1>My Orders</h1>
    <% if !@myOrders.nil? %>
      <% @myOrders.each do |order| %>
      <div class = "card card-block col-xs-4 col-xs-offset-4">
        <h3><%= order["shirt"].product %></h3></br>
        
        <div class="row col-xs-4 col-xs-offset-4">
          <div class="col-xs-6">
            <img  src=<%=order["shirt"].image_url%> style="height:100px;width:100px;"></img>
          </div>
          <div class="col-xs-6 ">
          <% @helper = [] %>
            <div class="col-xs-6">
              <% @productColor = order["product"]["colors"].select{|color| color["name"] == order["shirt"].color} %>
                <% if @productColor==@helper %>
                  <img id = "shirtHomeImg" src=<%=order["product"]["image"]["url"]%> style="height:100px;width:100px;"></img>
                <% else %>
                  <% @imageColor = @productColor[0]["images"].select{|image| image["label"] == "Front"} %>
                  <% if @imageColor==@helper %>
                    <% @imageColor = @productColor[0]["images"][0] %>
                  <% end %>
                  <img id = "shirtHomeImg" src=<%= @imageColor[0]["url"] %> style="height:100px;width:100px;"></img>
                <% end %>  
            </div>
          </div>
        </div></div></br></br>
       <% end %>
     <% end %>
  
</div>