config/routes.rb
Rails.application.routes.draw do
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  post '/cart/checkout' => 'cart#checkout'
  resources :checkout
  resources :orders
  post '/checkout' => 'checkout#create'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'users#new'
  

  resources :users
  resources :groups
  resources :memberships
  resources :shirts
  post 'shirts/show_product'
  post 'shirts/show'
  post 'shirts/upload'

end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
    
    #attr_accessor :design_id, :group_id, :end_date, :delivery_address

   
    def self.create_shirt!(shirt_params)
        
        shirt_params[:design_id]= loop do
          token = SecureRandom.urlsafe_base64
          break token unless Shirt.exists?(:design_id => token)
        end
        puts shirt_params
        @test = Shirt.create!(shirt_params)
        
    end
    
    
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController


  def shirt_params
    params.require(:shirt).permit(:group_id, :design_id, :end_date, :delivery_address, :image_url, :color, :product, :price)
  end

  def show
    if params[:category].nil?
      redirect_to shirts_path
    else
      @category=params[:category]
      @products = JSON.parse(RestClient.get("https://test_pNOw-AjW1Pz73UNPKb3F2g:@api.scalablepress.com/v2/categories/#{params[:category]}"))["products"]
      
      
    end
    @groups = Group.where(:admin_id => current_user.id) #need this here for navbar to work on shirts pages
  end

  def show_product
    if params[:product].nil?
      redirect_to shirts_path
    else
      @product = JSON.parse(RestClient.get("https://test_pNOw-AjW1Pz73UNPKb3F2g:@api.scalablepress.com/v2/products/#{params[:product]}"))
      
    end
    @groups = Group.where(:admin_id => current_user.id) #need this here for navbar to work on shirts pages
  end
  
  

  def index
    cat = JSON.parse(RestClient.get("https://test_pNOw-AjW1Pz73UNPKb3F2g:@api.scalablepress.com/v2/categories"))
    @categories = cat.select {|category| category["type"]=="Garment"}
    @groups = Group.where(:admin_id => current_user.id) #need this here for navbar to work on shirts pages
  end

  def new
 
    @shirtProduct = JSON.parse(RestClient.get("https://test_pNOw-AjW1Pz73UNPKb3F2g:@api.scalablepress.com/v2/products/#{params[:shirt][:product]}"))
    params[:shirt][:group_id]=cookies[:group_id]
    
    
    if shirt_params[:price].to_f < 0
      return
    end
    testShirt = Shirt.create_shirt!(shirt_params)
    redirect_to authenticated_root_path
  end

  def create
    
  end

  def edit
    
  end

  def update
    
  end

  def destroy
    
  end
  
  def upload
    
  end

end

app/views/shirts/index.html.erb
<div class = "text-center">
  <%= render "layouts/navbar" %>
  
  <div class ="row">
    <h2>Garment Options</h2>
    <div class = "col-md-4 col-md-offset-4">
      <hr>
    </div>
  </div>
 
  <%= form_tag shirts_show_path do %>
    <div class = "row">
      <div class = "col-md-6 col-md-offset-3">
        <div class = "card">
          <table id="products">
            <thead>
              <tr>
                <th style="text-align:left">Name</th>
                <th style="text-align:center">Select</th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td style="text-align:left">
                    <%= category["name"] %>
                  </td>
                  
                  <td style="text-align:center">
                    <%= radio_button_tag "category", "#{category["categoryId"]}" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class ="row">
      <div class = "col-md-4 col-md-offset-4">
        <%= submit_tag 'Choose this category', class: "submitTag btn btn-success btn-block", :id => "category button" %>
      </div>
    </div>
  <% end %>
  

</div>

app/views/shirts/new.html.erb
<div class = "text-center">
  
  <h2>Create Group</h2>
  <%= form_tag groups_path do %>
  <div class = "row">
    <div class = "form-group col-md-4 col-md-offset-4">
      <div class = "field">
        <%= text_field :group,'group_name', placeholder: 'Group Name',:id => 'signup_user' %>
        <%= text_field :group, 'admin_id',:id => 'signup_email',:value => current_user.id,:readonly => true %>
        <%= label :group, :admin_id, 'ID of the Administrator for Group' %> <br/>
        <%= submit_tag 'Create Group', class: "submitTag btn btn-success btn-block", :id => 'signup_create' %>
        <%= link_to 'Cancel', authenticated_root_path %>
      </div>
    </div>
  </div>
    
    
    
  <% end %>
</div><div class = "text-center">
  
  <h2>Create Group</h2>
  <%= form_tag groups_path do %>
  <div class = "row">
    <div class = "form-group col-md-4 col-md-offset-4">
      <div class = "field">
        <%= text_field :group,'group_name', placeholder: 'Group Name',:id => 'signup_user' %>
        <%= text_field :group, 'admin_id',:id => 'signup_email',:value => current_user.id,:readonly => true %>
        <%= label :group, :admin_id, 'ID of the Administrator for Group' %> <br/>
        <%= submit_tag 'Create Group', class: "submitTag btn btn-success btn-block", :id => 'signup_create' %>
        <%= link_to 'Cancel', authenticated_root_path %>
      </div>
    </div>
  </div>
    
    
    
  <% end %>
</div>

app/views/shirts/show.html.erb
<div class = "text-center">
  <%= render "layouts/navbar" %>
  
  <h2><%= @category%></h2>
  
  
  <div class = "col-md-6 col-md-offset-3">
    <hr>
    <%= form_tag shirts_show_product_path do %>
      <div class = "card">
          <table id="products">
            <thead>
              <tr>
                <th style="text-align:left">Product Name</th>
                <th style="text-align:center">Image</th>
                <th style="text-align:center">Select</th>
              </tr>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td style="text-align:left">
                    <%= product["name"] %>
                  </td>
                  <td>
                    <% if !product["image"].nil? %>
                      <%= image_tag product["image"]["url"], :id => "shirtsShowImg" %>
                    <% end %>
                  </td>
                  
                  <td style="text-align:center">
                    <%= radio_button_tag "product", "#{product["id"]}" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <%= submit_tag 'Choose this Product', class: "submitTag btn btn-success btn-block", :id => "category button" %>
    <% end %>
  </div>
  
</div>

app/views/shirts/show_product.html.erb
<%= render "layouts/navbar" %>

<% if flash[:notice] %>
    <div class="flash_message" id="notice">
      <%= flash[:notice] %>
    </div>
<% end %>

<h2><%=@product["name"] %></h2>
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <hr>
  </div>
</div>

  <div class = "row">
    <div class = "col-md-3 col-md-offset-3">
      <%= image_tag @product["image"]["url"], :id => "productImg"%>
    </div>
    <div class = "col-md-3">
      <p><b><%=@product["description"] %></b></p>
      </br>
      <h3>Colors</h3>
  <%= form_tag new_shirt_path, multipart: true, :method => 'get' do %>
    <select name="shirt[color]" id="shirt_color">
      <% @product["colors"].each do |color| %>
        <option value="<%=color["name"]%>"><%=color["name"]%></option> 
        
      <% end %>
    </select>
</div>
</div>

  </br>
  <div class = "row">
    <div class = "col-md-4 col-md-offset-4">
      <div class = "field">
        <%= text_field :shirt,:delivery_address, placeholder: 'Address for delivery' %>
      </div>
      <div class = "field">
        <%= text_field :shirt,:end_date, placeholder: 'End date of order (mm/dd/yyyy)'  %>
      </div>
      <div class = "field">  
        <%= text_field :shirt, :price, placeholder: '$  .  ' %>
      </div>
      <div class = "field">
        <%= text_field :shirt, :image_url, placeholder: 'Image URL' %>
      </div>
      <div class = "field">
        <%= text_field :shirt, :product, :value=> params[:product], :hidden => true %>
      </div>
    </div>
  </div>
  <div class = "row">
    <div class = "col-md-6 col-md-offset-3">
      <%= submit_tag 'Choose this Item', class: "submitTag btn btn-success btn-block", :id => "product button" %>
    </div>
  </div>
  <% end %>


  <div id="imgModal" class="modal">
    <span class="close">×</span>
    <img class="modal-content" id="modalimg">
  </div>
  
  <script>
    // Get the modal
    var modal = document.getElementById('imgModal');
    
    // Get the image and insert it inside the modal - use its "alt" text as a caption
    var img = document.getElementById('productImg');
    var modalImg = document.getElementById("modalimg");
    img.onclick = function(){
        modal.style.display = "block";
        modalImg.src = this.src;
    }
    
    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];
    
    // When the user clicks on <span> (x), close the modal
    span.onclick = function() { 
        modal.style.display = "none";
    }
  </script>


  