config/routes.rb
Rails.application.routes.draw do
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  post '/cart/checkout' => 'cart#checkout'
  resources :checkout
  resources :orders
  post '/checkout' => 'checkout#create'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'users#new'
  

  resources :users
  resources :groups
  resources :memberships
  resources :shirts
  post 'shirts/show_product'
  post 'shirts/show'
  post 'shirts/upload'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse"> 
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'EZSHIRTS', authenticated_root_path, class: "navbar-brand"%>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if params[:controller] == 'home' %>"><%= link_to 'Home', authenticated_root_path%></li>
        <li class="dropdown <%= 'active' if params[:controller] == 'groups' %>"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><%=current_user.firstname%>'s Groups <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @groups.each do |group| %>
              
               <li><%= link_to(group.group_name,group_path(group,:group_id => group.group_id)) %></li>
              
            <% end %>
            <li class="divider"></li>
            <li><%= link_to('Create Group', new_group_path, :method => :get, :id => 'createGroup') %></li>
          </ul>
        </li>
        <li class="<%= 'active' if params[:controller] == 'cart' %>"><%= link_to 'Cart', cart_path %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete, :id=>'Logout') %></li>
      </ul>
    </div>
  </nav>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeltTeam8</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield(:header) if content_for? :header %>
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>

  <%= yield %>
  <p class="notice text-center"><%= notice %></p>
  <p class="alert text-center"><%= alert %></p>

</body>
</html>